language: java
jdk:
- openjdk8
install: gradle wrapper
os:
- linux
before_install:
  - wget https://services.gradle.org/distributions/gradle-6.1.1-bin.zip
  - unzip -qq gradle-6.1.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.1.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
  
jobs:
  include:
    - stage: Compilation
      script: gradle build
    - stage: Compilation
      script: gradle createRelease
deploy:
  provider: releases
  token: $GITHUB_TOKEN_KEY
  skip_cleanup: true
  file: 
    - "$TRAVIS_BUILD_DIR/build/release/Test-Keys.zip"
    - "$TRAVIS_BUILD_DIR/build/release/Test-Keys.tar"
    - "$TRAVIS_BUILD_DIR/build/release/Test-Keys.tar.MD5"
    - "$TRAVIS_BUILD_DIR/build/release/Test-Keys.zip.MD5"
  on:
    tags: true
